/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import BUS.CTHDBUS;
import BUS.ChiTietNhapBUS;
import BUS.HoaDonBUS;
import BUS.MenuBUS;
import BUS.TaiKhoanBUS;
import DTO.ChiTietNhapDTO;
import DTO.HoaDonDTO;
import DTO.MenuDTO;
import DTO.TaiKhoanDTO;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author CHINH
 */
public class PhieuNhap_Form extends javax.swing.JFrame {
    private ArrayList<ChiTietNhapDTO> list;
    private ArrayList<MenuDTO> list1;
    DefaultTableModel model;
    SimpleDateFormat fdate = new SimpleDateFormat("dd/MM/yyyy");
    /** Creates new form PhieuNhap_Form */
    public PhieuNhap_Form() {
        initComponents();
        this.setResizable(false); 
        ImageIcon img = new ImageIcon("src//Image//phieunhap.png");
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
        tbPhieuNhap.setShowGrid(true);
        list = new ChiTietNhapBUS().getListPhieuNhap();
        list1= new MenuBUS().getListMenu();
        model = (DefaultTableModel) tbPhieuNhap.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "MaNhap", "MaMon", "SoLuong", "DVT", "TongTien","NgayNhap"
        });
        tbPhieuNhap.getColumnModel().getColumn(0).setPreferredWidth(40);
        clearTable();
        showTable();
       // bt2.setEnabled(false);
        bt3.setEnabled(false);
    }
    public String getMaNhap(){
        String x=list.get(list.size()-1).getMaNhap().toString();
        String xx=x.substring(3);
        int ma=Integer.valueOf(xx);
        ma++;
        x=x.replaceFirst(xx,String.valueOf(ma)); 
        return x;
    }
    public String getDate(){
        Date x= new Date();
        return fdate.format(x);
    }
    public void showTable() {
        int i=1;
        for (ChiTietNhapDTO s : list) {
            model.addRow(new Object[]{
                i++, s.getMaNhap(), s.getMaMon(), s.getSoLuong(), s.getDVT(),s.getTongTien(),s.getNgayNhap()
            });
        }
     }
     public void clearTable() {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhieuNhap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMaNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDVT = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Phiếu Nhập");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phieunhap.png"))); // NOI18N
        jLabel1.setText("Quản Lý Phiếu Nhập");

        tbPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhieuNhap);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key.png"))); // NOI18N
        jLabel2.setText("Mã Nhập");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key1.png"))); // NOI18N
        jLabel3.setText("Mã Món");

        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/money.png"))); // NOI18N
        jLabel4.setText("Số Lượng");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/amount.png"))); // NOI18N
        jLabel5.setText("ĐVT");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tongtien.png"))); // NOI18N
        jLabel6.setText("Tổng Tiền");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key.png"))); // NOI18N
        jLabel7.setText("Ngày Nhập");

        txtDate.setDateFormatString("dd/MM/yyyy\n");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thêm.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        bt2.setText("Refresh");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-bin-24.png"))); // NOI18N
        bt3.setText("Xóa");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exel.png"))); // NOI18N
        jButton2.setText("Nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ly", "Chai" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(bt3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed
    public boolean hasNum(String a){
        Pattern kitudb=Pattern.compile("[~!@#$%^&*)(-=/*+?<>;:']");
        Matcher ktdb=kitudb.matcher(a);
        if(ktdb.find()){
            return false;
        }
        else{
        for(char c:a.toCharArray()){
            if(Character.isDigit(c)) {
                return false;
            }
        }
        }
        return true;
    }
    public boolean hasWord(String a){
        Pattern spec=Pattern.compile("[~!@#$%^&*)(?<>;:']");
        Matcher ktdb=spec.matcher(a);
        if(ktdb.find()){
            return false;
        }
        else{
        for(char c:a.toCharArray()){
            if(Character.isLetter(c)) {
                return false;
            }
        }
        }
        return true;
    }
    public boolean validid1(String a){
        Pattern spec=Pattern.compile("[~!@#$%^&*)(?<>;:']");
        Matcher ktdb=spec.matcher(a);
        if(ktdb.find()){
            return false;
        }
        else if(!a.startsWith("MN")){
            return false;
        }
        return true;
    }
    public boolean validid2(String a){
        Pattern spec=Pattern.compile("[~!@#$%^&*)(?<>;:']");
        Matcher ktdb=spec.matcher(a);
        if(ktdb.find()){
            return false;
        }
        else if(!a.startsWith("MaMon")){
            return false;
        }
        return true;
    }
    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed
     public void showDB1(){
        int selectrow=tbPhieuNhap.getSelectedRow();
        txtMaNhap.setText(tbPhieuNhap.getValueAt(selectrow,1).toString());
        txtMaMon.setText(tbPhieuNhap.getValueAt(selectrow,2).toString());
        txtSoLuong.setText(tbPhieuNhap.getValueAt(selectrow,3).toString());
        txtTongTien.setText(tbPhieuNhap.getValueAt(selectrow,5).toString());
        Date date;
        try {
            date = new  SimpleDateFormat("dd/MM/yyyy").parse((String)model.getValueAt(selectrow,6));
            txtDate.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDon_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tbPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuNhapMouseClicked
        // TODO add your handling code here:
        showDB1();
    }//GEN-LAST:event_tbPhieuNhapMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!validid1(txtMaNhap.getText())){
            JOptionPane.showMessageDialog(null,"Mã nhập không hợp lệ");
        }
        else if(!validid2(txtMaMon.getText())){
            JOptionPane.showMessageDialog(null,"Mã món không hợp lệ");
        }
        else if(!hasWord(txtSoLuong.getText())){
            JOptionPane.showMessageDialog(null,"Số lượng không hợp lệ");
        }
        else{
        ChiTietNhapDTO s= new ChiTietNhapDTO();
        int soluongton=Integer.valueOf(txtSoLuong.getText().toString());
        s.setMaNhap(txtMaNhap.getText());
        s.setMaMon(txtMaMon.getText());
        s.setDVT(txtDVT.getSelectedItem().toString());
        s.setSoLuong(Integer.valueOf(txtSoLuong.getText().toString()));
        s.setTongTien(Integer.valueOf(txtTongTien.getText().toString()));
        MenuDTO x= new MenuDTO();
        x.setMaMon(txtMaMon.getText());
        for (int i=0;i<list1.size();i++){
            if (list1.get(i).getMaMon().toString().equals(txtMaMon.getText())){
                    x.setTenMon(list1.get(i).getTenMon().toString());
                    x.setDonGia(Integer.valueOf(list1.get(i).getDonGia().toString()));
                    soluongton+=list1.get(i).getSoLuongTon();
                    x.setSoLuongTon(soluongton);
                    if (new MenuBUS().updateMenu(x)){
                        System.out.println("....");
                    }
                    break;
                    
            }
        }
        s.setNgayNhap(fdate.format(txtDate.getDate()));
        if (new ChiTietNhapBUS().addPhieuNhap(s)) {
            JOptionPane.showMessageDialog(null, "Thêm Thành Công.");
            list.add(s);
        } else {
            JOptionPane.showMessageDialog(null, "Thêm Thất Bại.");
        }
        clearTable();
        list = new ChiTietNhapBUS().getListPhieuNhap();
        showTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
       /* ChiTietNhapDTO s= new ChiTietNhapDTO();
        int soluongton=Integer.valueOf(txtSoLuong.getText().toString());
        s.setMaNhap(txtMaNhap.getText());
        s.setMaMon(txtMaMon.getText());
        s.setDVT(txtDVT.getText());
        s.setSoLuong(Integer.valueOf(txtSoLuong.getText().toString()));
        s.setTongTien(Integer.valueOf(txtTongTien.getText().toString()));
        s.setNgayNhap(fdate.format(txtDate.getDate()));
        MenuDTO x= new MenuDTO();
        x.setMaMon(txtMaMon.getText());
        for (int i=0;i<list1.size();i++){
            if (list1.get(i).getMaMon().toString().equals(txtMaMon.getText())){
                    x.setTenMon(list1.get(i).getTenMon().toString());
                    x.setDonGia(Integer.valueOf(list1.get(i).getDonGia().toString()));
                    soluongton+=list1.get(i).getSoLuongTon();
                    x.setSoLuongTon(soluongton);
                    if (new MenuBUS().updateMenu(x)){
                        System.out.println("....");
                    }
                    break;
                    
            }
        }
        if (new ChiTietNhapBUS().updatePhieuNhap(s)) {
            JOptionPane.showMessageDialog(null, "Sửa Thành Công.");
        } else {
            JOptionPane.showMessageDialog(null, "Sửa Thất Bại.");
        }
        clearTable();
        list = new ChiTietNhapBUS().getListPhieuNhap();
        showTable();*/
       clearTable();
       showTable();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
      ChiTietNhapDTO s= new ChiTietNhapDTO();
        s.setMaNhap(txtMaNhap.getText());
        if (new ChiTietNhapBUS().deletePhieuNhap(s)) {
            JOptionPane.showMessageDialog(null, "Xóa Thành Công.");
        } else {
            JOptionPane.showMessageDialog(null, "Xóa Thất Bại.");
        }
        clearTable();
        list = new ChiTietNhapBUS().getListPhieuNhap();
        showTable();
    }//GEN-LAST:event_bt3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelJTableImport=null;
        String filePath = "E:";
        JFileChooser excelFileChooser = new JFileChooser(filePath);
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                
                excelFile = excelFileChooser.getSelectedFile();
                clearTable();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelJTableImport = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet=excelJTableImport.getSheetAt(0);
                for (int row=5;row<excelSheet.getLastRowNum();row++){
                    XSSFRow excelRow=excelSheet.getRow(row);
                    String excelMaMon=excelRow.getCell(0).toString();
                    String excelSoLuong=excelRow.getCell(1).toString();
                    String excelDVT=excelRow.getCell(2).toString();
                    String excelTongTien=excelRow.getCell(3).toString();
                    Date excelNgayNhap=excelRow.getCell(4).getDateCellValue();
                    Integer SoLuong=(int)Double.parseDouble(excelSoLuong);
                    Integer TongTien=(int)Double.parseDouble(excelTongTien);
                    String NgayNhap = fdate.format(excelNgayNhap);
                    ////  Thêm phiếu nhập CSDL
                    
                    ChiTietNhapDTO s= new ChiTietNhapDTO();
                    int soluongton=SoLuong;
                    s.setMaNhap(getMaNhap());
                    s.setMaMon(excelMaMon);
                    s.setDVT(excelDVT);
                    s.setSoLuong(SoLuong);
                    s.setTongTien(TongTien);
                    MenuDTO x= new MenuDTO();
                    x.setMaMon(excelMaMon);
                    for (int i=0;i<list1.size();i++){
                        if (list1.get(i).getMaMon().toString().equals(excelMaMon)){
                                x.setTenMon(list1.get(i).getTenMon().toString());
                                x.setDonGia(Integer.valueOf(list1.get(i).getDonGia().toString()));
                                soluongton+=list1.get(i).getSoLuongTon();
                                x.setSoLuongTon(soluongton);
                                if (new MenuBUS().updateMenu(x)){
                                    System.out.println("....");
                                }
                                break;

                        }
                    }
                    s.setNgayNhap(NgayNhap);
                    if (new ChiTietNhapBUS().addPhieuNhap(s)) {
                        //JOptionPane.showMessageDialog(null, "Thêm Thành Công.");
                        list.add(s);
                    } else {
                        JOptionPane.showMessageDialog(null, "Lỗi.");
                    }
                  //  System.out.println(excelMaNV);
                    //System.out.println(excelMatKhau);
                    model.addRow(new Object[]{
                        row+1,getMaNhap(),excelMaMon,SoLuong,excelDVT,TongTien,NgayNhap
                    });
                    /* for (int column=0;column<excelRow.getLastCellNum();column++){
                        XSSFCell excelCell=excelRow.getCell(column);
                        System.out.println(excelCell.getStringCellValue());
                    }*/
                    
                   
                }
                 JOptionPane.showMessageDialog(null,"Nhập thành công.");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

    }
    

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhap_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhap_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPhieuNhap;
    private javax.swing.JComboBox<String> txtDVT;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtMaNhap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

}
