/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CTHDBUS;
import BUS.HoaDonBUS;
import DTO.CTHDDTO;
import DTO.HoaDonDTO;
import GUI.TrangChu_Form;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHINH
 */
public class ThanhToan_Form extends javax.swing.JFrame {
    public TrangChu_Form trangchu;
    private ArrayList<CTHDDTO> list1;
    DefaultTableModel model;
    SimpleDateFormat ft = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy ");
    SimpleDateFormat ftime = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat fdate = new SimpleDateFormat("dd/MM/yyyy");
    JTable tbMenu = new JTable();
    String MaNV;
    
    /**
     * Creates new form ThanhToan_Form
     */
    
   
    public ThanhToan_Form(String tien, String manv ) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("src//Image//thanhtoan.png");
        this.setIconImage(img.getImage());
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("src//Image//thanhtoan111.jpg").getImage().getScaledInstance(290,150, Image.SCALE_DEFAULT));
        lbThanhToan.setIcon(imageIcon1);
        txtTongTien.setText(tien);
        list1= new CTHDBUS().getListCTHD();
       
        model = (DefaultTableModel) tbMenu.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Tên Món","Số Lượng", "Đơn Giá"
        });
        showDBbb();
        MaNV = manv;
        
    }
   
     public String getMaHoaDon(){
        String x=list1.get(list1.size()-1).getMaHoaDon().toString();
        String xx=x.substring(4);
        int ma=Integer.valueOf(xx);
        //ma++;
        x=x.replaceFirst(xx,String.valueOf(ma)); 
        return x;
    }
    
    public void OK(){
        int x=Integer.valueOf(txtTongTien.getText());
        int y = 0;
        if (txtTienKhachDua.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập tiền!!!");
        } else{ y=Integer.valueOf(txtTienKhachDua.getText());  
        
        if (x>y) JOptionPane.showMessageDialog(null,"Thiếu tiền!!!");
            else {
                txtTienThua.setText(String.valueOf(y-x));
            }
    }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTienThua = new javax.swing.JTextField();
        lbThanhToan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh Toán");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tongtien.png"))); // NOI18N
        jLabel1.setText("Tổng Tiền:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thanhtoan.png"))); // NOI18N
        jLabel2.setText("Tiền Khách Đưa");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tienthua.png"))); // NOI18N
        jLabel3.setText("Tiền Thừa");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/xacnhan.png"))); // NOI18N
        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
            .addComponent(lbThanhToan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lbThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void showDBbb(){
       String ss= getMaHoaDon();
       int k=0;
       Object[] row= new Object[6];
        for (int i=0;i<list1.size();i++){
            if (list1.get(i).getMaHoaDon().toString().equals(ss)){
                k++;
                row[0]=k;
                row[1]=list1.get(i).getMaHoaDon();
                row[2]=list1.get(i).getTenMon();
                row[3]=list1.get(i).getMaMon();
                row[4]=list1.get(i).getSoLuong();
                row[5]=list1.get(i).getGia();
                model.addRow(row);
            }
        }
    }
      public String getDate(){
        Date x= new Date();
        return fdate.format(x);
    }
     public void SaveToPDF(String path) throws FileNotFoundException, IOException,DocumentException{
        Document doc = new Document();
        String u = "Thanh tien: "+ txtTongTien.getText();
        String u1= "Tien khach tra: "+ txtTienKhachDua.getText();
        String u2= "Tien thua: "+ txtTienThua.getText();
        File font= new File("VietFont\\vuTimes.ttf");
        PdfWriter.getInstance(doc,new FileOutputStream(path+".pdf"));
        doc.open();
        BaseFont bf= BaseFont.createFont(font.getAbsolutePath(),BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        Font fo=new Font(bf,12);
        Font fo2=new Font(bf,30);
        PdfPTable table=new PdfPTable(4);
        Paragraph title= new Paragraph("--------------------\n"+"Coffe House"+"\n--------------------");
        title.setFont(fo2);
        title.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        doc.add(title);
        doc.add(new Phrase("\n",fo));
        doc.add(new Phrase("\n",fo));
        doc.add(new Phrase("Mã nhân viên: "+ MaNV +"\n",fo));
        doc.add(new Phrase("Mã Hóa Đơn: "+getMaHoaDon()+"\n",fo));
        addHeader(table,fo);
        int row=tbMenu.getRowCount();
        for(int i=0;i<row;i++){  
            String mamon=tbMenu.getValueAt(i,0).toString();
            String tenmon=tbMenu.getValueAt(i,1).toString();
            String soluong=tbMenu.getValueAt(i,2).toString();
            String dongia=tbMenu.getValueAt(i,3).toString();
            String[] ro={mamon,tenmon,soluong,dongia};
            addRow(table,ro,fo);
        }
        
        Paragraph sum=new Paragraph(u);
        sum.setFont(fo);
        sum.setAlignment(com.itextpdf.text.Element.ALIGN_RIGHT);
        Paragraph sum1=new Paragraph(u1);
        sum1.setFont(fo);
        sum1.setAlignment(com.itextpdf.text.Element.ALIGN_RIGHT);
        Paragraph sum2=new Paragraph(u2);
        sum2.setFont(fo);
        sum2.setAlignment(com.itextpdf.text.Element.ALIGN_RIGHT);
        Paragraph line=new Paragraph("----------------------------------------------------------------\n");
        line.setAlignment(1);
        Paragraph time= new Paragraph("Ngày thanh toán: "+getDate());
        time.setFont(fo);
        time.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        doc.add(table);
        doc.add(sum);
        doc.add(sum1);
        doc.add(sum2);
        doc.add(line);
        doc.add(time);
        doc.close();
    }
    private static void addHeader(PdfPTable table, Font font){
        Stream.of("Mã món", "Tên món", "Số Lượng", "Đơn Giá")
                   .forEach(columnTitle ->{
                   PdfPCell header= new PdfPCell();
                   header.setBackgroundColor(BaseColor.WHITE);
                   header.setBorderColor(BaseColor.WHITE);
                   header.setBorderWidth((float) 2.5);
                   header.setPhrase(new Phrase(columnTitle,font));
                   table.addCell(header);
                   });
    }
    private static void addRow(PdfPTable table,String[] row,Font font){
        table.addCell(new Paragraph(row[0],font));
        table.addCell(new Paragraph(row[1],font));
        table.addCell(new Paragraph(row[2],font));
        table.addCell(new Paragraph(row[3],font));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OK();
        if(!txtTienThua.getText().equals("")) JOptionPane.showMessageDialog(null,"Thanh toán thành công!!!");
        try {
            SaveToPDF(getMaHoaDon());
        } catch (IOException ex) {
            Logger.getLogger(ThanhToan_Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ThanhToan_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTienKhachDuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           OK();
      }
    }//GEN-LAST:event_txtTienKhachDuaKeyPressed

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ThanhToan_Form("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbThanhToan;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
